services:

  warehouse:
    build:
      context:    .docker/
      dockerfile: spark.Dockerfile
    ports:
    - "10000:10000"
    - "4040:4040"
    volumes:
    - ./volumes/lakehouse/standardized:/opt/spark/parquet
  metabase:
    volumes:
    - ./volumes/metabase-data:/metabase-data
    environment:
    - MB_DB_FILE=/metabase-data/metabase.db
    ports:
    - 3000:3000
    image: metabase/metabase
    restart: always
    depends_on:
    - warehouse
  etl:
    build:
      context:    .github/actions/data
      dockerfile: Dockerfile
    profiles:
    - etl
    env_file:
    - data.env
    volumes:
    - ./volumes/lakehouse/raw:/data/raw/${REFERENCE}
    - ./volumes/lakehouse/standardized:/data/standardized/${REFERENCE}
    environment:
    - REFERENCE=${REFERENCE}
    - SINCE=${SINCE}
    - TARGET=${TARGET}